###
GET http://localhost:3003/api/users

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "fecfecfec",
    "name": "FirstName LastName",
    "password": "helsinki"
}

### Other user for token validations
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "doubleUser",
    "name": "Javalin Scripta",
    "password": "crouchet"
}

### Password Invalid
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "passwordCortita3",
    "name": "Password Cortita",
    "password": "he"
}

### Username Invalid
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "ka",
    "name": "Username Cortito",
    "password": "helsinki"
}

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "root",
    "name": "Superuser",
    "password": "salainen"
}